### ISSUE TITLE
lol this isn't even a bypass

### ISSUE THREAD

**Issue by Swag1400** [zkcm1337/Discord-rate-limit-bypass#1]
this isnt even "bypassing" anything you're just waiting the respected amount of time between rates, some which aren't even accurate

**Comment by zkcm1337** [comment]
bypassing means "go past or round" in other terms i made something to avoid rate lim but its just with a catchy name, in my experience you cannot actually bypass it, if you know how you can bypass a disconnect from the gateway because of doing too many events at a specific time then sure do it or share it with people. Im only here and i only posted my code to gh because to help others who dont know how to avoid it. If you have anything else to say or ask then feel free to do that.

**Comment by zkcm1337** [comment]
if this doesnt get a response in 3 days im closing the "issue"
